#!/usr/bin/env python

# kano-usertools
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

import grp
import pwd
import sys
import os
import subprocess
import shutil
import json

from kano_settings.keyboard.keyboard_config import set_keyboard
from kano_settings.config_file import file_replace
from kano_settings.boot_config import set_config_value, set_config_comment


def run(cmd):
    return subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()


def run_term_on_error(cmd):
    o, e = run(cmd)
    if e:
        print e
        quit(1)


def delfile(filename):
    if os.path.exists(filename):
        os.remove(filename)


def userexists(username):
    pwdall = pwd.getpwall()
    names = [u.pw_name for u in pwdall]
    return username in names


def get_new_kanouser_id():
    users = pwd.getpwall()
    uids = []
    for u in users:
        uids.append(u.pw_uid)
    i = 1000
    while i in uids:
        i += 1
    return i


# super-safe solution to make sure kanousers group always exists
run('groupadd kanousers -f')

# start
tempfile = "/var/tmp/newuser"
givencommand = ' '.join(sys.argv)
kanomembers = grp.getgrnam('kanousers').gr_mem

# migrate from old environment, where kanouser was UID=1000
try:
    old_user = pwd.getpwuid(1000).pw_name
    if old_user not in kanomembers:
        # print old_user + " not in kano users, adding"
        run('usermod -a -G kanousers {}'.format(old_user))
        kanomembers = grp.getgrnam('kanousers').gr_mem
except:
    pass

# check for wrong usage
if len(sys.argv) == 1:
    print "wrong usage", givencommand
    quit(1)

# get kano user names
if sys.argv[1] == 'names':
    print ' '.join(kanomembers)

# get number of kano users
elif sys.argv[1] == 'number':
    print len(kanomembers)

# get first user's name
elif sys.argv[1] == 'firstuser':
    print kanomembers[0]

# save new user's name
elif sys.argv[1] == "savename":

    if len(sys.argv) != 3:
        print "wrong usage", givencommand
        quit(1)

    delfile(tempfile)
    data = {}
    name = sys.argv[2]
    data['name'] = name

    fout = json.dumps(data)
    w = open(tempfile, 'w')
    w.write(fout)
    w.close()

# load new user's name
elif sys.argv[1] == "loadname":

    if len(sys.argv) != 2:
        print "wrong usage", givencommand
        quit(1)

    fin = open(tempfile).read()
    data = json.loads(fin)
    print data['name']

# load new user's name
elif sys.argv[1] == "testname":

    if len(sys.argv) != 2:
        print "wrong usage", givencommand
        quit(1)

    json_ok = True
    try:
        fin = open(tempfile).read()
        data = json.loads(fin)
    except IOError, e:
        json_ok = False
    except ValueError, e:
        json_ok = False

    returncode = int(json_ok and 'name' in data)
    print(returncode)

# create new user
elif sys.argv[1] == "createuser":

    if len(sys.argv) != 2:
        print "wrong usage", givencommand
        quit(1)

    if not os.path.exists(tempfile):
        print "temp file doesn't exists"
        quit(1)

    fin = open(tempfile).read()
    data = json.loads(fin)

    # username
    username = data['name']
    if userexists(username):
        quit(0)

    # id
    userid = get_new_kanouser_id()
    # start creating the user
    USER_PASSWORD = "kano"
    USER_GROUPS = "adm,dialout,cdrom,audio,users,sudo,video,games,plugdev,input,kanousers"

    # Create the new user
    home = '/home/' + username
    home_bak = '/home/' + username + '.bak'

    if os.path.exists('/home/' + username):
        print "home folder exists, moving {} to {}".format(home, home_bak)
        shutil.move(home, home_bak)

    cmd = 'useradd -m -u {} -s /bin/bash {}'.format(userid, username)
    run_term_on_error(cmd)

    cmd = 'echo "{}:{}" | chpasswd'.format(username, USER_PASSWORD)
    run_term_on_error(cmd)

    cmd = 'usermod -G "{}" {}'.format(USER_GROUPS, username)
    run_term_on_error(cmd)

    delfile(tempfile)

# delete user at boot
elif sys.argv[1] == 'deleteuser':

    # Get user from last line of /etc/profile.d/autostart-kano-init.sh file
    user, _ = run('tail -1 /etc/profile.d/autostart-kano-init.sh')
    # Remove the #
    user = user[1:].strip()
    if (not kanomembers) or (user not in kanomembers):
        # user not found
        quit(1)
    # kill all process from user
    cmd = 'killall -KILL -u {}'.format(user)
    run(cmd)
    # Delete user
    cmd = 'userdel -r {}'.format(user)
    run(cmd)
    # Remove user from last line of /etc/profile.d/autostart-kano-init.sh file
    run('sed -i \'$ d\' /etc/profile.d/autostart-kano-init.sh')

# delete user in an interactive way
elif sys.argv[1] == 'deleteuser-interactive':

    if not kanomembers:
        print "No users to delete"
        quit(1)

    print 'users: ' + ', '.join(kanomembers)

    user = ''
    while not user:
        user = raw_input('Which user: ')
        if user not in kanomembers:
            print "Sorry, you mistyped something, please try again!"
            user = ''

    # kill all process from user
    cmd = 'killall -KILL -u {}'.format(user)
    run(cmd)

    deletehome = ''
    if os.path.exists('/home/' + user):
        while not deletehome:
            deletehome = raw_input("Do you also want to delete the user's home folder?\n"
                                   "This includes all saved games and changes kept locally!\n"
                                   "Y (yes) / N (no): ")
            deletehome = deletehome.lower()
            if deletehome not in ['y', 'n']:
                print "Sorry, you mistyped something, please try again!"
                deletehome = ''

    if deletehome == 'y':
        cmd = 'userdel -r {}'.format(user)
    else:
        cmd = 'userdel {}'.format(user)

    o, e = run(cmd)
    if '/var/mail' not in e:
        print e

    o, e = run('kano-init.sh singlemulti')
    print o, e

# deleting all users, needed for reset
elif sys.argv[1] == 'deleteallusers':

    for user in kanomembers:
        # killing all process from user
        cmd = 'killall -KILL -u {}'.format(user)
        run(cmd)

        # removing user and home folder
        cmd = 'userdel -r {}'.format(user)
        o, e = run(cmd)
        if '/var/mail' not in e:
            print e

    run('rm -rf /home/*')

# restoring factory settings
elif sys.argv[1] == 'restorefactory':

    # removing wifi settings
    try:
        os.unlink('/etc/kwifiprompt-cache.conf')
    except:
        pass

    # set the keyboard to default
    set_keyboard('', 'generic')

    # setting the audio to analogue
    amixer_from = "amixer -c 0 cset numid=3 [0-9]"
    amixer_to = "amixer -c 0 cset numid=3 1"

    file_replace("/etc/rc.audio", amixer_from, amixer_to)
    set_config_value('hdmi_ignore_edid_audio', 1)
    set_config_value('hdmi_drive', None)

    # resetting HDMI settings
    set_config_value('disable_overscan', 1)
    set_config_value('overscan_left', 0)
    set_config_value('overscan_right', 0)
    set_config_value('overscan_top', 0)
    set_config_value('overscan_bottom', 0)
    set_config_value('hdmi_pixel_encoding', 2)
    set_config_value('hdmi_group', None)
    set_config_value('hdmi_mode', None)
    set_config_comment('kano_screen_used', 'xxx')

    # resetting overclocking settings
    set_config_value('arm_freq', 950)
    set_config_value('core_freq', 450)
    set_config_value('sdram_freq', 450)
    set_config_value('over_voltage', 6)

# mistyped command
else:
    print "wrong usage", givencommand
    quit(1)
