#!/bin/bash

# postrm
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

case "$1" in

    remove|upgrade)
        # Remove sudoers config file
        rm /etc/sudoers.d/kano-init_conf

        # As a precaution, so a safe cleanup takes place
        systemctl disable overture
        systemctl stop overture
        ;;
esac

#DEBHELPER#

exit 0
