#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2

TMP_FILE=/tmp/kano-init_conf
TMP_FILE2=/tmp/kano-idle-daemon_conf
TMP_FILE3=/tmp/design-museum-reset

case "$1" in
    configure)
        groupadd kanousers -f

        # Create custom sudoers file
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/kano-init" > $TMP_FILE
        chown root:root $TMP_FILE
        # The file permissions must be set to 0440
        chmod 0440 $TMP_FILE
        mv $TMP_FILE /etc/sudoers.d/

        # Create custom sudoers file
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/kano-idle-daemon" > $TMP_FILE2
        chown root:root $TMP_FILE2
        # The file permissions must be set to 0440
        chmod 0440 $TMP_FILE2
        mv $TMP_FILE2 /etc/sudoers.d/

        # Create custom sudoers file
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/design-museum-reset" > $TMP_FILE3
        chown root:root $TMP_FILE3
        # The file permissions must be set to 0440
        chmod 0440 $TMP_FILE3
        mv $TMP_FILE3 /etc/sudoers.d/

        ;;
esac


#DEBHELPER#

exit 0
